interface ReviewData {
    summary: string;
    suggestions: string[];
}

/**
 * @param reviewData - An object containing the review summary and a list of suggestions.
 * @returns A formatted string in Markdown format.
 */

export function formatReviewToMarkdown(reviewData: ReviewData): string {
    let markdown = "# Code Review Summary\n\n";
    markdown += "## Overall Summary\n\n";
    markdown += `${reviewData.summary}\n\n`;

    if (reviewData.suggestions && reviewData.suggestions.length > 0) {
        markdown += "## Detailed Suggestions\n\n";
        reviewData.suggestions.forEach((suggestion, index) => {
            markdown += `${index + 1}. ${suggestion}\n`;
        });
    }

    markdown += "\n---\n\n*Generated by AI Code Review Agent*\n";
    return markdown;
}
